pod 'AFNetworking', "~> 1.x.x"
pod 'Reachability'
pod 'MBProgressHUD'
pod 'Reveal-iOS-SDK', :configuration => ['Debug']
pod 'HockeySDK', '~> 3.8'
pod 'DRPSlidingTabView', '~> 0.2'
pod 'TTTAttributedLabel'

pod 'Realm'
